### ISSUE TITLE
Въпрос относно финалните проекти

### ISSUE THREAD

**Issue by DianaGeorgievaa** [SwiftFMI/swift_2019_2020#10]
Като тема за финален проект бях избрала играта със заровете, а в таблицата пише проекта Дама. Това в резултат на допълнително разпределение ли е, с цел равномерно разделяне на проектите между участниците в курса, или е възникнална грешка при попълването на таблицата? Също така ние сами ли трябва да изберем коя от двете части да разработим - "Задачи по проект №1"/  "Задачи по проект №2", или вие ще ни разпределите и за тях?

**Comment by heitara** [comment]
Вие давате предпочитание, системата (формула в ексел за произволни числа) дава финално решение. Понеже студентите се записват по различно време е възможно нормалното разпределение да е нарушено. 
Изборът за коя част от проекта - може да го направите вие. Моля, посочете го после.
