### ISSUE TITLE
Въпрос относно проект "Дама"

### ISSUE THREAD

**Issue by trvulkov** [SwiftFMI/swift_2019_2020#11]
Според условието координатите се формират от буква измежду A, B и C и число измежду 1, 2 и 3. Това ни дава 9 възможни позиции, което ще е достатъчно за _three men's morris_, но тук имплементираме _nine men's morris_ и ни трябват 24 позиции. 
В уикипедия статията, посочена на края на условието, има изображение на дъска на която координатите ползват буквите от A до G и числата от 1 до 7, което ще е достатъчно за 24те позиции.
![morris](https://user-images.githubusercontent.com/66442116/84169640-83fb2980-aa81-11ea-843f-9965c258fdbd.PNG)
Така ли всъщност трябва да се имплементира?

**Comment by heitara** [comment]
На мене ми харесва така предложената нотация. T.e. белите са на следните полета:
```
d1, d2, e3, e4, e5
```

**Comment by heitara** [comment]
След като отразим промените в документацията, ще го затворим този въпрос, като считаме, че предложената нотация остава валидна.

**Comment by spasbilyarski** [comment]
Промяната е нанесена в описанието на проекта.
