### ISSUE TITLE
Лекции за swift package manager

### ISSUE THREAD

**Issue by alien1976** [SwiftFMI/swift_2019_2020#13]
Здравейте,

Ще може ли да качите записки от лекциите за swift package manager, или поне базовите команди за уиндоус сетъпа?

Благодаря,
Калоян

**Comment by heitara** [comment]
@alien1976 може да погледнеш първоначалната версия на записките в следния PR - https://github.com/SwiftFMI/swift_2019_2020/pull/14 Има нужда от още работа, но основните елементи са там. Ако имаш коментари и въпроси, моля задавай ги директно в PR-a, за да можем да попълним пропуските и неяснотите.
cc: @ivanov-dragomir
