### ISSUE TITLE
Проект Дама

### ISSUE THREAD

**Issue by AleksandarK837** [SwiftFMI/swift_2019_2020#15]
Здравейте, да попитам за координатите за проект Дама: Как точно се представят координатите на дъската, защото като гледам дъската е нещо от сорта на 6х7, а са дадени като възможни координати само A,B,C  като хоризонтални и 1,2,3 като вертикални, няма ли да има в такъв случай повтарящи се координати в другата половина на дъската? Не би ли трябвало да се представят по подобие на шахматната дъска, примерно от A - F и от 1 - 7 или обратно?

**Comment by terzievk** [comment]
7х7 e... Виж тук https://github.com/SwiftFMI/swift_2019_2020/issues/11

**Comment by spasbilyarski** [comment]
Здравей, направена е промяна по заданието на проекта. Можеш да видиш промяната [тук](https://github.com/SwiftFMI/swift_2019_2020/blob/master/projects/nine-mens-morris.md).
