### ISSUE TITLE
Съдържание на github репото

### ISSUE THREAD

**Issue by trvulkov** [SwiftFMI/swift_2019_2020#20]
Репото трябва ли да съдържа нещо друго освен папката Sources (и съответно .swift файловете в нея) и файловете Package.swift и README.md? 
На лекциите се спомена че тестове не са задължителни, така че да включваме ли Tests папката и няколкото файла в нея, които SPM си генерира (аз всъщност си закоментирах съответните редове в Package.swift, така че нямам testTarget въобще)?
За проектите, при които се прави изпълнимо приложение, да включваме ли .build папката (изпълнимите файлове предполагам са платформено-специфични, така че няма много смисъл)?

**Comment by heitara** [comment]
Разгледай `.gitignore` файла. Той не включва `.build` папката понеже всеки може да я генерира от source-а.

Ако няма тестове, няма смисъл да се добавят файлове свързани с тях. За пълнота, може да се оставят основните тестове от генерирания проект. Не е проблем.

Добре е да добавите таговете, които са важни, за да може всеки друг да свали вашата версия и да може да я стартира успешно. Това може да го проверите и вие в нова папка.
