### ISSUE TITLE
Zombie dice игра

### ISSUE THREAD

**Issue by krasimirak** [SwiftFMI/swift_2019_2020#29]
Въпроса ми е при хвърлянето на зарове ако бъдат хвърлени стъпки тези зарове остават за следващото хвърляне (от 3 зара) ако играча избере да хвърля отново? Или отделно имаме команда за повторното хвърляне само на тези зарове със стъпките?

**Comment by ivanov-dragomir** [comment]
Заровете със стъпките може да се хвърлят отново само ако играчът избере да продължи. Те участват в новата "ръка", която винаги е 3 на брой. 
Пример:
Играч тегли 3 зара и хвърля 1х мозък (точка) и 2х стъпки
1. Играчът спира и бележи 1 точка
или
2. Играчът тегли още един зар и хвръля новата "ръка" от 3 зара (1 нов + 2 стъпки от предното хвърляне)
