### ISSUE TITLE
Въпроси относно втора задача от първото домашно

### ISSUE THREAD

**Issue by angelbeshirov** [SwiftFMI/swift_2019_2020#3]
1. Има ли отрицателни числа в първоначалния израз и ако да, винаги ли съответното число е в скоби, т.е. (-число)?
2. Има ли изрази в които броя на затварящите скоби е различен от броя на операторите освен изрази от типа (число)?
3. За всяка бинарна операция ли има отваряща и затваряща скоба?

**Comment by heitara** [comment]
1. Има отрицателни числа. Примерно: (-2 + 3). Отново правилен вход с отрицателни числа е (-2 * -2).
2. Не. Броят на операците и броят на скобите са фиксирани за всеки израз в отношение 1:2. Само когато имаме отрицателни числа, нещата са по-различни. Но там - е унарна операция, за да може да се запише негативно число.
3. Да. Валиден е следния израз:  (((34 + 5) * 4) + 2). Имаме скоби при всяка бинарна операция. Това **((34 + 5) * 4 + 2)** не е валиден израз. -2 само е валиден израз, както и всяко цяло число.
