### ISSUE TITLE
Оценки & нанасяне

### ISSUE THREAD

**Issue by Hristosko** [SwiftFMI/swift_2019_2020#31]
Здравейте,

исках да попитам как ще разберем резултатите и кога ще е нанасянето на оценките?

**Comment by alien1976** [comment]
@heitara @spasbilyarski @ivanov-dragomir , в случай, че не сте видяли този въпрос. Доста хора се интересуваме.
Благодаря!

**Comment by heitara** [comment]
Нанасяне на оценки ще има, когато има пак редовни занятия. За сега ще избягваме събиранията от много хора на едно място. Оценките ще ги пратим до канцеларията когато всички са проверени с протоколите. Тази седмица ще пратим оценките на всички студенти, които ще се явяват на държавен изпит. Понеже държавния изпит е след две седмици.

Всички крайни оценки до момента ще ги обявим в гитхъб днес вечерта. Проверяването отнема доста време и вероятно всички ще бъдат оценени най-рано след две седмици.

**Comment by Hristosko** [comment]
Благодаея за отговора.
Съжалявам, че толкова досаждах, но ще се явявам да държавен изпит.
Все още нямам оценка - предполагам днес/утре ще качите още?
В случай че има нещо - фн. 45256

**Comment by heitara** [comment]
@Hristosko трябва да имаш оценка [тук](https://github.com/SwiftFMI/swift_2019_2020/blob/master/projects/final.grades.md).

**Comment by Hristosko** [comment]
Да, благодаря.
